### ISSUE TITLE
AutoChatScript的问题

### ISSUE THREAD

**Issue by cloveric** [MaoXiaoYuZ/Long-Novel-GPT#5]
是运行AutoChatScript后，会在chatgpt的聊天框里自动输入This Say a is Test!。之后会看到鼠标自动逐行往下去找聊天框发送的的那个按钮，但是鼠标自动到了聊天框那个发送的按钮的时候，鼠标会在按钮旁边周围运动，导致This Say a is Test!这句话一直没有发出去。

我不知是不是这个原因，在浏览器的demo设置中，在chatgpt base_url填写http://localhost:8000/v1/  ，后，测试结果反馈：
User:Say this is a test
(ERROR)chatgpt:list() takes no keyword arguments

**Comment by MaoXiaoYuZ** [comment]
”鼠标会在按钮旁边周围运动“是在检测按钮区间，这一步只发生在初始化，初始化之后会保存按钮图片，之后只要页面不移动位置，就不需要重新初始化了。

还有就是我刚刚推送了一个AutoChatScript更新，你更新下再试试

**Comment by MaoXiaoYuZ** [comment]
python demo.py
运行后出现了：
User(q to quit, r to resubmit): 
这个吗？

**Comment by cloveric** [comment]
> python demo.py 运行后出现了： User(q to quit, r to resubmit): 这个吗？

出现了，如果这时候按r，输入你要说的话，就报错

User(q to quit, r to resubmit): r
         resubmit:我欧克
waiting submit button...
submit button found!
waiting submit button...
submit button found!
Traceback (most recent call last):
  File "D:\google drive\python\AutoChatScript\demo.py", line 5, in <module>
    auto_script.demo()
  File "D:\google drive\python\AutoChatScript\chatgpt_auto_script.py", line 484, in demo
    response = self.resubmit(prompt)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\google drive\python\AutoChatScript\chatgpt_auto_script.py", line 274, in resubmit
    button_left_top, button_right_bottom, line_height = self.estimate_resubmit_button_reigon(response)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\google drive\python\AutoChatScript\chatgpt_auto_script.py", line 45, in wrapper
    raise e
  File "D:\google drive\python\AutoChatScript\chatgpt_auto_script.py", line 43, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\google drive\python\AutoChatScript\chatgpt_auto_script.py", line 401, in estimate_resubmit_button_reigon
    for left_top_text in response.split("\r\n"):
                         ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'


但是比较有意思的是，如果在一个已经发生的对话里，你这时候启动AutoChatScript，它会找到你上面已经聊天的修订按钮（那个小铅笔），然后可以点击小铅笔成功，然后把你之前的发言改成Say this is a test，之后就可以正常进行，可以继续在程序中，按r输入，得到反馈。

但是在全新的对话中缺不可以

**Comment by MaoXiaoYuZ** [comment]
当然，r是指重新提交；你直接输入hello，回车即可，这样才是正常submit。
