### ISSUE TITLE
出现Error JSONDecodeError错误，但是json格式并没发现有问题

### ISSUE THREAD

**Issue by yzlltyyh** [MaoXiaoYuZ/Long-Novel-GPT#8]
为什么json格式没错也一直报Error JSONDecodeError ( Expecting value : line 1 column 2 (char 呀，重试了好多遍，也重启了好几次，都稳定复现ε(┬┬﹏┬┬)3
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/109973085/67da64ee-e17c-49ab-a0a1-d98f0bfa871c)
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/109973085/21e762b9-d39c-4556-8796-f4dbd3db59d2)

**Comment by yzlltyyh** [comment]
这是过程
```
现在你是一个小说家，正在和我一起合作来创作小说大纲。
接下来让我们一步一步来，你需要遵照我的指令逐步完成整个大纲的创作，期间我还可能让你根据我的意见进行修改。
对话的内容如果过长，我会让你进行总结并省略部分对话内容。侦探少女和她的猫
欢快，跌宕起伏，可爱，二次元


不要急于得出结论，让我们先一步一步的思考


当然，让我们一步步来构建这个故事。首先，我们需要为这个侦探少女和她的猫设定一些基本的背景信息。

角色设定：
侦探少女：我们给她一个響亮的名字，比如说“樱井莉莉”。她是一位年轻而聪明的高中生，对解谜充满热情。莉莉具有观察细节的天赋，总能在不起眼的线索中发案件的关键。
她的猫：猫的名字叫做“摩卡”，是一只拥有神秘力量的黑猫。摩卡能够理解人类语言，并且偶尔会给莉莉一些超自然的提示。
. 故事背景：

故事发生在一个充满魔法和科技的二次元世界，这个世界虽然看起来和我们的现实世界相似，但是隐藏着许多奇幻的元素。莉莉活在这个世界的一个小城市中，城市既有现代化的设施，也有古老的神秘之处。
故事的开始：
故事从莉莉收到一个神秘信件开始，信件中提示一起即将发生的罪案。莉莉决定调查这个案件，摩卡自然是她的小助手。
接下来，我们可以根据这个基础设定开始构思故事的主线，包括案件的性质、到的挑战、以及莉莉和摩卡是如何解决问题的。我们也可以设定一些重要的副角色，比如莉莉的朋友、家人，或者是与案件相关的人物。


指示：现在需要你对小说设定进行创作。

你需要以JSON格式输出新的小说大纲。
输出格式：
{
"分析": "<这里进行分析/反思>", // 这个键必须存在，用于分析/反思
"<设定名>": { // 设定名可以是：人名，物体名，功法名，地点名，某个概念的名称等等。
"操作": "<填 新增/修改>",
"分析": "<这里进行分析/反思>",
"描述": "<在该字符串中创作该设定的具体内容>" // 描述必须是一个字符串，不能为字典或列表
},
"<设定名>": {
"操作": "<填 保留/删除>" // 保留或删除设定不需要填写分析和描述
},
// 更多设定，除了新增设定名，其余和输入中设定名一一对应
}



{
  "分析": "为了创造一个充满活力、跌宕起伏且可爱的二次元风格的侦探故事，我们为主角莉莉和她的猫摩卡设定了一个魔法与科技并存的界。这种设定不仅为故事提供了广阔的想象空间，还能吸引喜欢奇幻元素和侦探故事的读者。接下来，我们将围绕这个背景，进一步丰富故事的节，增加角色深度，以及构建悬念和冲突，使故事更加引人入胜。",
  "樱井莉莉": {
    "操作": "保留"
  },
  "摩卡": {
    "操作": "保留"
  },
 "案件的性质": {
    "操作": "新增",
    "分析": "案件的性质需要足够吸引人，同时能展示主角的侦探技能和摩卡的超自然能力。选择一个案件，既能激发者的好奇心，也能合理地串联起整个故事的发展。",
    "描述": "这个案件是关于一系列神秘消失事件，这些事件看似毫无联系，但实际上背后隐藏着一个巨大阴谋。这些消失事件都与古老的传说和城市中一些古老的神秘地点有关。"
  },
  "莉莉的朋友": {
    "操作": "新增",
    "分析": "为莉莉设计一位或位好朋友，不仅可以增加故事的人际关系层次，还能在解决案件过程中提供帮助，增加故事的动态性和多样性。",
    "描述": "莉莉的好朋友是一位充活力且对科技极其着迷的少年，名叫“林健太”。健太的科技天赋在莉莉解决案件的过程中发挥了重要作用，他能制造各种侦探设备帮助莉莉。"
 },
  "古老的传说": {
    "操作": "新增",
    "分析": "古老的传说不仅是案件背后的重要线索，也是连接现代与古老神秘之间的桥梁。通过探索这些传，可以进一步丰富故事背景，增加故事的深度和趣味性。",
    "描述": "这个传说讲述的是一位古代的魔法师，他在城市的地下藏有一个秘密的魔法库，面藏有能够控制时间和空间的神秘物品。这位魔法师的灵魂被封印在城市的某个古老地点，等待着合适的时机复苏。"
  }
}
```

**Comment by MaoXiaoYuZ** [comment]
能贴出下控制台错误信息吗，就是运行python demo/app.py的那个控制台

**Comment by yzlltyyh** [comment]
不好意思，这个问题似乎是因为我使用的是逆向的API，格式不对齐导致的，使用官方API和官转API则可以正常使用了o(*^▽^*)┛
终于可以用GPT写长小说了，感谢开发者<(￣︶￣)↗[GO!]
~弱弱问一句，考虑支持Claude3嘛，那个文笔比较好且写出来的东西更有人味一点。~
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/gradio/queueing.py", line 501, in call
_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/gradio/route_utils.py", line 253, in c
all_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/gradio/blocks.py", line 1695, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/gradio/blocks.py", line 1247, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/gradio/utils.py", line 516, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/gradio/utils.py", line 509, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/gradio/utils.py", line 492, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/envs/lngpt/lib/python3.10/site-packages/gradio/utils.py", line 675, in gen_wrapper
    response = next(iterator)   
  File "/root/Long-Novel-GPT/demo/tab_outline_writer.py", line 95, in wrapper
    raise gr.Error(e)
gradio.exceptions.Error: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
```
